### ISSUE TITLE
FMI: "ModelDescription" namespace

### ISSUE THREAD

**Issue by robha67** [FGHaider/pyssp_standard#11]
Question: Should there be a FMI or model description class in the standard.py file?

**Comment by FGHaider** [comment]
Sorry for such a late reply, I have chosen to omit a FMI model description to focus the library on the different SSP-specific file formats. If you think otherwise, could you provide some references and an explanation of what features you would imagine implemented?

**Comment by robha67** [comment]
I will have some use case where I would like to test to updated the Model strycture elements of the ModelDescription file based on some empirical testing of the FMU.

**Comment by FGHaider** [comment]
Hi, could please specify what sections of https://fmi-standard.org/docs/3.0/ you would like implemented?

**Comment by robha67** [comment]
Hi again. Section 2.4.8, see Figure 30. However, it is not necessarily easy to deduce how the ModelStructure element of the xml is thought to work without examples. I will try to generate some example.

**Comment by FGHaider** [comment]
Hi again, would you say this request was resolved in the latest release 0.6.1?

**Comment by robha67** [comment]
I havent tested ghe feature yet . Unless the plan fails completely, then this is something that we wills start using in the fall.  But I am closing this issue and then create new ones if addietional features are needed.
